WIP: Add column writer
crphang/orc pull request #1
Opened 2020-01-26 12:13 UTC by Crphang

2020-01-26 13:59 UTC, kelindar requested changes

2020-01-26 13:59 UTC, kelindar commented on writer.go
> +	"gitlab.myteksi.net/gophers/go/dispatcher/grab-x/commons/utils/math"
Wrong import

2020-01-28 06:47 UTC, Crphang commented on writer.go
> +	"gitlab.myteksi.net/gophers/go/dispatcher/grab-x/commons/utils/math"
Fixed

2020-01-28 09:16 UTC, kelindar approved these changes

2020-01-28 09:17 UTC, merged